# Generated by Django 3.2.23 on 2024-01-14 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0029_auto_20240103_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='idtag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 14, 13, 31, 36, 461187)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_cadastro',
            field=models.DateField(default=datetime.date(2024, 1, 14)),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_publicacao',
            field=models.DateField(default=datetime.date(2024, 1, 14)),
        ),
    ]
