# Generated by Django 3.2.23 on 2024-01-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='idtag',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
